CREATE DATABASE IF NOT EXISTS typing_speed_db;
USE typing_speed_db;

CREATE TABLE IF NOT EXISTS scores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    wpm INT NOT NULL,
    accuracy INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
